package com.found404.gameoflife.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import com.found404.gameoflife.dto.RewardCreateDTO;
import com.found404.gameoflife.dto.RewardResponseDTO;
import com.found404.gameoflife.entity.Reward;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR, unmappedSourcePolicy = ReportingPolicy.IGNORE)
public interface RewardMapper {

    RewardResponseDTO toDto(Reward reward);

    List<RewardResponseDTO> toDtos(List<Reward> rewards);

    @Mapping(target = "user", ignore = true) // set in service
    @Mapping(target = "id", ignore = true) // generated by DB
    @Mapping(target = "createdAt", ignore = true)
    Reward toEntity(RewardCreateDTO dto);

}
